apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: ntp
spec:
  containers:
  - name: postgres
    image: postgres
    resources:
      limits:
        memory: "800Mi"
      requests:
        memory: "400Mi"
    env:
      - name: POSTGRES_PASSWORD
        value: mysecretpassword
    ports:
      - containerPort: 5432
        name: postgres
        protocol: TCP
    command: ["postgres"]
