apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres-api
  namespace: ntp
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: postgres-api
    spec:
      containers:
        - name: postgres-api
          image: postgres-api
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initalDelaySeconds: 8
            periodSeconds: 5
