apiVersion: v1
kind: Service
metadata:
  name: postgres-api
  namespace: ntp
  labels:
    app: postgres-api
spec:
  type: ClusterIP
  ports:
   - port: 5000
  selector:
   app: postgres-api