apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scanner
  namespace: ntp
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: scanner
    spec:
      containers:
        - name: scanner
          image: scanner:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
            initalDelaySeconds: 8
            periodSeconds: 5
