apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scanner
  namespace: ntp
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: scanner
    spec:
      containers:
        - name: scanner
          image: ntp-scanner:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5000

