apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scheduler
  namespace: ntp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image: scheduler:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initalDelaySeconds: 8
            periodSeconds: 5
